##sqlite settings

# Add `gem 'sqlite3'` to your Gemfile.
#
base: &base
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  pool: 5
  timeout: 5000

production:
  <<: *base
  database: db/production.sqlite3

development:
  <<: *base
  database: db/development.sqlite3

test:
  <<: *base
  database: db/test.sqlite3

##Mysql settings

#base: &base
  #adapter: mysql
  #encoding: utf8
  #reconnect: false
  #pool: 5
  #username: ror
  #password: pass
  #host: localhost

#production:
  #<<: *base
  #database: ror_production

#development:
  #<<: *base
  #database: ror_development

#test:
  #<<: *base
  #database: ror_test
